name: Tests

on: [push, pull_request]

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - {name: Python 3.8,  python:  '3.8',}
          - {name: Python 3.9,  python:  '3.9',}
          - {name: Python 3.10, python: '3.10',}
          - {name: Python 3.11, python: '3.11',}
          - {name: Python 3.12, python: '3.12',}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Display Python version
        run: python -m pip install -r requirements/dev.txt
      - name: Pytest
        run: python -m pytest
      - name: Upload coverage reports to Codecov
        if: matrix.python == '3.12'
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
